objects/DM_Automated_Payment_Setup__c.object
<CustomObject>
    <fields>
        <fullName>DM_CL_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DM CL Contract</label>
        <referenceTo>DM_Loan_Account__c</referenceTo>
        <relationshipLabel>DM Automated Payment Setup</relationshipLabel>
        <relationshipName>DM_Automated_Payment_Setups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DM Automated Payment Setup</label>
    <nameField>
        <label>DM Automated Payment Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Automated Payment Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Charge__c.object
<CustomObject>
    <fields>
        <fullName>DM_CL_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DM CL Contract</label>
        <referenceTo>DM_Loan_Account__c</referenceTo>
        <relationshipLabel>DM Charges</relationshipLabel>
        <relationshipName>DM_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DM Charge</label>
    <nameField>
        <label>DM Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Interest_Posting_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>DM_CL_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DM CL Contract</label>
        <referenceTo>DM_Loan_Account__c</referenceTo>
        <relationshipLabel>DM Interest Posting Transaction</relationshipLabel>
        <relationshipName>DM_Interest_Posting_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DM Interest Posting Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Interest Posting Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Loan_Account__c.object
<CustomObject>
    <fields>
        <fullName>DM_Error__c</fullName>
        <label>DM Error</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DM_Invalid_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If system identify any data issues with this lending account, the reasons will be displayed on the top of lending account and this flag will be checked.
Once the issues are fixed, this flag will be unchecked by system.
User should not modify this flag.</inlineHelpText>
        <label>DM Invalid Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DM_Is_Migrated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DM Is Migrated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DM_Valid_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DM Valid Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migrated_CL_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Migrated CL Contract</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>DM CL Contract</relationshipLabel>
        <relationshipName>DM_CL_Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Migration_Status__c</fullName>
        <label>Migration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DM CL Contract</label>
    <nameField>
        <label>DM Loan Con Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM CL Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Loan_Disbursal_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>DM_CL_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DM CL Contract</label>
        <referenceTo>DM_Loan_Account__c</referenceTo>
        <relationshipLabel>DM Loan Disbursal Transactions</relationshipLabel>
        <relationshipName>DM_Loan_Disbursal_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DM Loan Disbursal Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Loan_Payment_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>CL_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CL Contract</label>
        <referenceTo>DM_Loan_Account__c</referenceTo>
        <relationshipLabel>DM Loan Payment Transactions</relationshipLabel>
        <relationshipName>DM_Loan_Payment_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DM_Automated_Payment_Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DM Automated Payment Setup</label>
        <referenceTo>DM_Automated_Payment_Setup__c</referenceTo>
        <relationshipLabel>DM Loan Payment Transactions</relationshipLabel>
        <relationshipName>DM_Loan_Payment_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DM_Is_Migrated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DM Is Migrated</label>
        <type>Checkbox</type>
    </fields>
    <label>DM Loan Payment Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Repayment_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>DM_Loan_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DM Loan Account</label>
        <referenceTo>DM_Loan_Account__c</referenceTo>
        <relationshipLabel>DM Repayment Schedules</relationshipLabel>
        <relationshipName>DM_Repayment_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DM_Valid_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DM Valid Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migration_Status__c</fullName>
        <label>Migration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DM Amortization Schedule</label>
    <nameField>
        <label>Dm Repayment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Amortization Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Repayment_Schedule_Summary__c.object
<CustomObject>
    <fields>
        <fullName>DM_CL_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DM CL Contract</label>
        <referenceTo>DM_Loan_Account__c</referenceTo>
        <relationshipLabel>DM Repayment Schedule</relationshipLabel>
        <relationshipName>DM_Repayment_Schedule_Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DM_Loan_Disbursal_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Repayment Schedule Record of which LDT</description>
        <inlineHelpText>This field is used only in case of FIT (Fund in Tranches) Loans. Every disbursal re-generates repayment schedule, this field keeps track of parent disbursal due to which record is created.</inlineHelpText>
        <label>DM Loan Disbursal Transaction</label>
        <referenceTo>DM_Loan_Disbursal_Transaction__c</referenceTo>
        <relationshipName>DM_Loan_Disbursal_Transaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DM Repayment Schedule</label>
    <nameField>
        <label>DM Amortization Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Repayment Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Tool_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Enable_Strategy_0__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Strategy-0?</label>
        <type>Checkbox</type>
    </fields>
    <label>DM Tool Settings</label>
</CustomObject>

objects/loan__Charge__c.object
<CustomObject>
</CustomObject>

objects/loan__Interest_Posting_Transaction__c.object
<CustomObject>
</CustomObject>

objects/loan__Loan_Disbursal_Transaction__c.object
<CustomObject>
</CustomObject>

objects/loan__Repayment_Schedule__c.object
<CustomObject>
</CustomObject>

classes/INV_DM_Data_Creation.cls
/******************************************************************************************************************
* Author: Samar Saha 
* Date: Oct - 2019
* Update History - 
*****************************************************************************************************************/ 
public class INV_DM_Data_Creation {
    public List<DM_Loan_Account__c> errorUpdate = new List<DM_Loan_Account__c>();
    Savepoint sp;
    public void DataCreation(List<DM_Loan_Account__c> dmList){
        system.debug('Inside DataCreation Method');        
        
        DM_Tool_Settings__c dmToolCS = DM_Tool_Settings__c.getOrgDefaults();
        
        for(DM_Loan_Account__c dmloan : dmList){
            Id parentId;
            errorUpdate.clear();
            System.debug('DM Contract Id --> '+ dmloan.Id);
            parentid = insertLoanContract(dmloan);
            
            system.debug('ParentId --> '+parentId);         
            
            if(parentId<>null){  
                //insert Amort sch         
                if(errorUpdate.isEmpty() || Test.isRunningTest()){         
                    System.debug('errorUpdate-->' +errorUpdate);        
                    if(!dmloan.DM_Repayment_Schedules__r.isEmpty() && dmToolCS.Migrate_Amort_Schedule__c == True){
                        insertRepaySchedule(dmloan.DM_Repayment_Schedules__r, parentId, dmloan.Id);
                    }
                }
                //insert Sch summary
                if(errorUpdate.isEmpty() || Test.isRunningTest()){                 
                    if(!dmloan.DM_Repayment_Schedule_Summarys__r.isEmpty() && dmToolCS.Migrate_RSS_Schedule__c == True){
                        insertRepaymentSS(dmloan.DM_Repayment_Schedule_Summarys__r, parentId, dmloan.Id);
                    }
                }
                //insert LPT
                if(errorUpdate.isEmpty() || Test.isRunningTest()){                 
                    if(!dmloan.DM_Loan_Payment_Transactions__r.isEmpty() && dmToolCS.Enable_Strategy_0__c == True){
                        insertLPT(dmloan.DM_Loan_Payment_Transactions__r, parentId, dmloan.Id);
                    }
                }
                //insert LDT
                if(errorUpdate.isEmpty() || Test.isRunningTest()){                 
                    if(!dmloan.dm_Loan_Disbursal_Transactions__r.isEmpty() && dmToolCS.Enable_Strategy_0__c == True){
                        insertLDT(dmloan.dm_Loan_Disbursal_Transactions__r, parentId, dmloan.Id);
                    }
                }
                //insert APS
                if(errorUpdate.isEmpty() || Test.isRunningTest()){                 
                    if(!dmloan.DM_Automated_Payment_Setups__r.isEmpty() && dmToolCS.Enable_Strategy_0__c == True){
                        insertAPS(dmloan.DM_Automated_Payment_Setups__r, parentId, dmloan.Id);
                    }
                }
                //insert charges                                
                if(errorUpdate.isEmpty() || Test.isRunningTest()){                 
                    if(!dmloan.DM_Charges__r.isEmpty() && dmToolCS.Enable_Strategy_0__c == True){
                        insertCharges(dmloan.DM_Charges__r, parentId, dmloan.Id);
                    }
                }
                
                //insert IPT
                if(errorUpdate.isEmpty() || Test.isRunningTest()){                 
                    if(!dmloan.DM_Interest_Posting_Transactions__r.isEmpty() && dmToolCS.Enable_Strategy_0__c == True){
                        insertIPT(dmloan.DM_Interest_Posting_Transactions__r, parentId, dmloan.Id);
                    }
                }
            }            
            
            if(!errorUpdate.isEmpty()){
                if(!Test.isRunningTest()){
                    update errorUpdate;
                }
            }else{
                Dm_Loan_Account__c dmLoanSuccess = new Dm_loan_Account__c(Id = dmloan.Id, 
                                                                          migration_status__c = 'Migrated', 
                                                                          DM_Error__c = '', 
                                                                          DM_Invalid_Data__c = false,
                                                                          DM_valid_Data__c = True,                                                                 
                                                                          DM_Is_Migrated__c = True, 
                                                                          Migrated_CL_Contract__C = parentId);
                update dmLoanSuccess;
            }
        }
        
    }//Data Creation
    
    private Id insertLoanContract(DM_Loan_Account__c dmloan){
        system.debug('insertLoanContract');
        INV_DM_MigrationHandler dmHandler = new INV_DM_MigrationHandler();
        loan__Loan_Account__c loan;
        if(dmloan != null){
            try{
                loan = dmHandler.Dm_FieldMapping_LoanAccount(dmloan);
                system.debug('loan after mapping'+loan);
                if(loan<>null){
                    sp = Database.setSavepoint();
                }
                //loanList.add(loan);
                insert loan;
                return loan.Id;
            }
            catch(Exception ex){
                errorUpdate.add(new DM_Loan_Account__c(Id = dmloan.Id, 
                                                       DM_Error__c = 'Exception Thrown - CL Contract - '+ ex.getMessage(), 
                                                       DM_Invalid_Data__c = True, 
                                                       DM_valid_Data__c = False, 
                                                       migration_status__c='Failed'));
                return null;
            }       
        }      
        return null;
    }//END insertLoanContract        
    
    private void insertRepaySchedule(List<DM_Repayment_Schedule__c> dm_RepaySch, Id parentId, Id dmloanID){
        system.debug('inside insertRepaySchedule');
        loan__Repayment_Schedule__c repaySch;
        INV_DM_MigrationHandler dmHandler = new INV_DM_MigrationHandler();
        List<loan__Repayment_Schedule__c> repaySchList = new List<loan__Repayment_Schedule__c>();
        if(!dm_RepaySch.isEmpty()){
            for(DM_Repayment_Schedule__c dmRepaySch : dm_RepaySch){
                repaySch = dmHandler.DM_StaticFieldMapping_RepaySCH(dmRepaySch,parentId);
                system.debug('rePaySch'+repaySch);
                if(repaySch<>null)
                    repaySchList.add(repaySch);
            }    
            try{
                if(!repaySchList.isEmpty()){
                    //Create SavePoint
                    insert repaySchList;
                }     
            }catch(Exception ex){
                errorUpdate.add(new DM_Loan_Account__c(Id = dmloanID, 
                                                       DM_Error__c = 'Exception Thrown - Repayment Schedule - '+ ex.getMessage(), 
                                                       DM_valid_Data__c = False, 
                                                       DM_Invalid_Data__c = True));
                Database.rollback(sp);
            }  
        }
    }        
    
    private void insertRepaymentSS(List<DM_Repayment_Schedule_Summary__c> dm_Rss, Id parentId, Id dmloanID){
        system.debug('inside insertRepaymentSS');
        loan__Repayment_Schedule_Summary__c rss;
        INV_DM_MigrationHandler dmHandler = new INV_DM_MigrationHandler();
        List<loan__Repayment_Schedule_Summary__c> rssList = new List<loan__Repayment_Schedule_Summary__c>();
        if(!dm_Rss.isEmpty()){
            for(DM_Repayment_Schedule_Summary__c dmrss : dm_Rss){
                system.debug('dm rss'+rss);
                rss = dmHandler.DM_StaticFieldMapping_rss(dmrss,parentId);
                system.debug('rss'+rss);
                if(rss<>null)
                    rssList.add(rss);
            }    
            try{
                if(!rssList.isEmpty()){
                    //Create SavePoint
                    insert rssList;
                }     
            }catch(Exception ex){
                errorUpdate.add(new DM_Loan_Account__c(Id = dmloanID, 
                                                       DM_Error__c = 'Exception Thrown - RSS - '+ ex.getMessage(), 
                                                       DM_valid_Data__c = False, 
                                                       DM_Invalid_Data__c = True, 
                                                       migration_status__c = 'Failed'));
                Database.rollback(sp);
            }//END Catch   
        }
    }//insertRepaymentSS
    
    private void insertLPT(List<dm_Loan_Payment_Transaction__c> dm_lpt, Id parentId, Id dmloanID){
        system.debug('inside insertLPT');
        loan__Loan_Payment_Transaction__c lpt;
        INV_DM_MigrationHandler dmHandler = new INV_DM_MigrationHandler();
        List<loan__Loan_Payment_Transaction__c> lptList = new List<loan__Loan_Payment_Transaction__c>();
        if(!dm_lpt.isEmpty()){
            for(dm_Loan_Payment_Transaction__c dmlpt : dm_lpt){
                lpt = dmHandler.DM_StaticFieldMapping_lpt(dmlpt,parentId);
                if(lpt<>null)
                    lptList.add(lpt);
            }    
            try{
                if(!lptList.isEmpty()){
                    //Create SavePoint
                    insert lptList;
                }     
            }catch(Exception ex){
                errorUpdate.add(new DM_Loan_Account__c(Id = dmloanID, 
                                                       DM_Error__c = 'Exception Thrown - LPT - '+ ex.getMessage(), 
                                                       DM_valid_Data__c = False, 
                                                       DM_Invalid_Data__c = True, 
                                                       migration_status__c = 'Failed'));                          
                Database.rollback(sp);
            }//END Catch   
        }
    }//END insertLPT
    
    private void insertLDT(List<dm_Loan_Disbursal_Transaction__c> dm_ldt, Id parentId, Id dmloanID){
        system.debug('inside insertLDT');
        loan__Loan_Disbursal_Transaction__c ldt;
        INV_DM_MigrationHandler dmHandler = new INV_DM_MigrationHandler();
        List<loan__Loan_Disbursal_Transaction__c> ldtList = new List<loan__Loan_Disbursal_Transaction__c>();
        if(!dm_ldt.isEmpty()){
            for(dm_Loan_Disbursal_Transaction__c dmldt : dm_ldt){
                ldt = dmHandler.DM_StaticFieldMapping_ldt(dmldt,parentId);
                if(ldt<>null)
                    ldtList.add(ldt);
            }//END For 
            try{
                if(!ldtList.isEmpty()){
                    //Create SavePoint
                    insert ldtList;
                }     
            }catch(Exception ex){
                //update the DM Record
                errorUpdate.add(new DM_Loan_Account__c(Id = dmloanID, 
                                                       DM_Error__c = 'Exception Thrown - LDT - '+ ex.getMessage(), 
                                                       DM_valid_Data__c = False, 
                                                       DM_Invalid_Data__c = True, 
                                                       migration_status__c = 'Failed'));                
                Database.rollback(sp);
            }//END Catch   
        }
    }//END insertLDT
    
    private void insertAPS(List<DM_Automated_Payment_Setup__c> dm_APS, Id parentId, Id dmloanID){
        system.debug('inside insertAPS');
        loan__Automated_Payment_Setup__c APS;
        INV_DM_MigrationHandler dmHandler = new INV_DM_MigrationHandler();
        List<loan__Automated_Payment_Setup__c> APSList = new List<loan__Automated_Payment_Setup__c>();
        if(!dm_APS.isEmpty()){
            for(DM_Automated_Payment_Setup__c dmAps : dm_APS){
                APS = dmHandler.DM_StaticFieldMapping_aps(dmAps,parentId);
                system.debug('APS'+aps);
                if(APS<>null)
                    APSList.add(APS);
            }    
            try{
                if(!APSList.isEmpty()){
                    //Create SavePoint
                    system.debug('APS BI');
                    insert APSList;
                }     
            }catch(Exception ex){
                errorUpdate.add(new DM_Loan_Account__c(Id = dmloanID, 
                                                       DM_Error__c = 'Exception Thrown - APS - '+ ex.getMessage(), 
                                                       DM_valid_Data__c = False, 
                                                       DM_Invalid_Data__c = True, 
                                                       migration_status__c = 'Failed'));                          
                Database.rollback(sp);
            }//END Catch   
        }
    }//END insertAPS
    
    private void insertCharges(List<DM_Charge__c> dm_Charges, Id parentId, Id dmloanID){
        system.debug('inside insertAPS');
        loan__Charge__c CHG;
        INV_DM_MigrationHandler dmHandler = new INV_DM_MigrationHandler();
        List<loan__Charge__c> chargeList = new List<loan__Charge__c>();
        if(!dm_Charges.isEmpty()){
            for(DM_Charge__c dmchrg : dm_Charges){
                CHG = dmHandler.DM_StaticFieldMapping_charge(dmchrg, parentId);
                system.debug('CHG'+chg);
                if(CHG <> null)
                    chargeList.add(CHG);
            }    
            try{
                if(!chargeList.isEmpty()){
                    //Create SavePoint
                    system.debug('CHG BI');
                    insert chargeList;
                }     
            }catch(Exception ex){
                errorUpdate.add(new DM_Loan_Account__c(Id = dmloanID, 
                                                       DM_Error__c = 'Exception Thrown - Charges - '+ ex.getMessage(), 
                                                       DM_valid_Data__c = False, 
                                                       DM_Invalid_Data__c = True, 
                                                       migration_status__c = 'Failed'));                          
                Database.rollback(sp);
            }//END Catch   
        }
    }//END insertCharges
    
    private void insertIPT(List<DM_Interest_Posting_Transaction__c> dm_IPT, Id parentId, Id dmloanID){
        system.debug('inside insertAPS');
        loan__Interest_Posting_Transaction__c IPT;
        INV_DM_MigrationHandler dmHandler = new INV_DM_MigrationHandler();
        List<loan__Interest_Posting_Transaction__c> IPTList = new List<loan__Interest_Posting_Transaction__c>();
        if(!dm_IPT.isEmpty()){
            for(DM_Interest_Posting_Transaction__c dmIpt : dm_IPT){
                IPT = dmHandler.DM_StaticFieldMapping_IPT(dmIpt,parentId);
                system.debug('IPT'+ipt);
                if(IPT<>null)
                    IPTList.add(IPT);
            }    
            try{
                if(!IPTList.isEmpty()){
                    //Create SavePoint
                    system.debug('IPT BI');
                    insert IPTList;
                }     
            }catch(Exception ex){
                errorUpdate.add(new DM_Loan_Account__c(Id = dmloanID, 
                                                       DM_Error__c = 'Exception Thrown - IPT - '+ ex.getMessage(), 
                                                       DM_valid_Data__c = False, 
                                                       DM_Invalid_Data__c = True, 
                                                       migration_status__c = 'Failed'));                          
                Database.rollback(sp);
            }//END Catch   
        }
    }//END insertIPT
    
}//END