objects/DM_Automated_Payment_Setup__c.object
<CustomObject>
    <label>DM Automated Payment Setup</label>
    <nameField>
        <label>DM Automated Payment Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Automated Payment Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Loan_Account__c.object
<CustomObject>
    <label>DM CL Contract</label>
    <nameField>
        <label>DM Loan Con Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM CL Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Loan_Disbursal_Transaction__c.object
<CustomObject>
    <label>DM Loan Disbursal Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Loan_Payment_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>DM_Automated_Payment_Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DM Automated Payment Setup</label>
        <referenceTo>DM_Automated_Payment_Setup__c</referenceTo>
        <relationshipLabel>DM Loan Payment Transactions</relationshipLabel>
        <relationshipName>DM_Loan_Payment_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DM Loan Payment Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Repayment_Schedule__c.object
<CustomObject>
    <label>DM Amortization Schedule</label>
    <nameField>
        <label>Dm Repayment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Amortization Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Repayment_Schedule_Summary__c.object
<CustomObject>
    <fields>
        <fullName>DM_Loan_Disbursal_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Repayment Schedule Record of which LDT</description>
        <inlineHelpText>This field is used only in case of FIT (Fund in Tranches) Loans. Every disbursal re-generates repayment schedule, this field keeps track of parent disbursal due to which record is created.</inlineHelpText>
        <label>DM Loan Disbursal Transaction</label>
        <referenceTo>DM_Loan_Disbursal_Transaction__c</referenceTo>
        <relationshipName>DM_Loan_Disbursal_Transaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DM Repayment Schedule</label>
    <nameField>
        <label>DM Amortization Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Repayment Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/INV_DM_MigrationJob.cls
/******************************************************************************************************************
* Author: Samar Saha
* Date: Oct - 2019
* Update History - 
*****************************************************************************************************************/ 
Global class INV_DM_MigrationJob implements Database.Batchable<sObject> 
{    
    public String migrationBatchType;
    public static String migrationBatchType;
    public List<DM_Loan_Account__c> errorUpdate = new List<DM_Loan_Account__c>();
    //public DM_Metadata_Config_Wrapper configWrapper;
  
    global INV_DM_MigrationJob(){
         //call the class and initialize the wrapper instance here.
         //configWrapper = ParserUtil.getParser();         
    }
    global INV_DM_MigrationJob(String batchType){
        //configWrapper = ParserUtil.getParser(); 
        migrationBatchType = batchType;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        INV_DM_SqlQueryGenerator sqlQuery = new INV_DM_SqlQueryGenerator();                
        //return Database.getQueryLocator(sqlQuery.GetQueryStringForMigration('DM_Repayment_Schedule_Summary__c;DM_Repayment_Schedule__c;DM_Loan_Payment_Transaction__c;DM_Automated_Payment_Setup__c;DM_Loan_Disbursal_Transaction__c;DM_Loan_Account__c'));
        return Database.getQueryLocator(sqlQuery.getQueryStringForMigrationStart());
    }

    global void execute(Database.BatchableContext BC, List<DM_Loan_Account__c> dmList) 
    {
        List<DM_Loan_Account__c> dmLoanScopeList = new List<DM_Loan_Account__c>();
        INV_DM_SqlQueryGenerator sqlQuery = new INV_DM_SqlQueryGenerator();        
        dmLoanScopeList = sqlQuery.getContractsForCurrentMigrationScope(dmList);
        system.debug('scope list '+dmList.size()+ 'list '+dmLoanScopeList);                       
        INV_DM_Data_Creation dataCreation;              
        dataCreation = new INV_DM_Data_Creation();
        dataCreation.DataCreation(dmLoanScopeList);
        system.debug('dataCreation Exit');        
    }
    
    global void finish(Database.BatchableContext BC) {
         system.debug('Finish INV_DM_MigrationJob Batch Job');
    }
    
}//Class End