objects/DM_Automated_Payment_Setup__c.object
<CustomObject>
    <label>DM Automated Payment Setup</label>
    <nameField>
        <label>DM Automated Payment Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Automated Payment Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Loan_Account__c.object
<CustomObject>
    <fields>
        <fullName>DM_Error__c</fullName>
        <label>DM Error</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DM_Invalid_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If system identify any data issues with this lending account, the reasons will be displayed on the top of lending account and this flag will be checked.
Once the issues are fixed, this flag will be unchecked by system.
User should not modify this flag.</inlineHelpText>
        <label>DM Invalid Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DM_Valid_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DM Valid Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migration_Status__c</fullName>
        <label>Migration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DM CL Contract</label>
    <nameField>
        <label>DM Loan Con Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM CL Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Loan_Disbursal_Transaction__c.object
<CustomObject>
    <label>DM Loan Disbursal Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Loan_Payment_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>DM_Automated_Payment_Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DM Automated Payment Setup</label>
        <referenceTo>DM_Automated_Payment_Setup__c</referenceTo>
        <relationshipLabel>DM Loan Payment Transactions</relationshipLabel>
        <relationshipName>DM_Loan_Payment_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DM Loan Payment Transaction</label>
    <nameField>
        <label>DM  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Loan Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Repayment_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>DM_Valid_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DM Valid Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migration_Status__c</fullName>
        <label>Migration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DM Amortization Schedule</label>
    <nameField>
        <label>Dm Repayment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Amortization Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DM_Repayment_Schedule_Summary__c.object
<CustomObject>
    <fields>
        <fullName>DM_Loan_Disbursal_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Repayment Schedule Record of which LDT</description>
        <inlineHelpText>This field is used only in case of FIT (Fund in Tranches) Loans. Every disbursal re-generates repayment schedule, this field keeps track of parent disbursal due to which record is created.</inlineHelpText>
        <label>DM Loan Disbursal Transaction</label>
        <referenceTo>DM_Loan_Disbursal_Transaction__c</referenceTo>
        <relationshipName>DM_Loan_Disbursal_Transaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DM Repayment Schedule</label>
    <nameField>
        <label>DM Amortization Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Repayment Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/INV_DM_ValidationJob.cls
/******************************************************************************************************************
* Author: Samar Saha
* Date: Oct - 2019
* Update History - 
*****************************************************************************************************************/ 
Global class INV_DM_ValidationJob implements Database.Batchable<sObject> 
{    
    public String migrationBatchType;
    public static String migrationBatchType;
    public List<DM_Loan_Account__c> validationUpdate = new List<DM_Loan_Account__c>();
    public map<id, DM_Loan_Account__c> loanmap = new map<id,DM_Loan_Account__c>();
    public List<INV_DM_ValidationWrapper> validationWrapperList = new List<INV_DM_ValidationWrapper>();
  
    global INV_DM_ValidationJob(){
         //call the class and initialize the wrapper instance here.
         //configWrapper = ParserUtil.getParser();         
    }
    global INV_DM_ValidationJob(String batchType){
        //configWrapper = ParserUtil.getParser(); 
        //migrationBatchType = batchType;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        INV_DM_SqlQueryGenerator sqlQuery = new INV_DM_SqlQueryGenerator();                
        //return Database.getQueryLocator(sqlQuery.GetQueryStringForValidation('DM_Repayment_Schedule_Summary__c;DM_Repayment_Schedule__c;DM_Loan_Payment_Transaction__c;DM_Automated_Payment_Setup__c;DM_Loan_Disbursal_Transaction__c;DM_Loan_Account__c'));
        return Database.getQueryLocator(sqlQuery.GetQueryStringForValidationStart());
    }

    global void execute(Database.BatchableContext BC, List<DM_Loan_Account__c> dmList) 
    {
        List<DM_Loan_Account__c> dmLoanScopeList = new List<DM_Loan_Account__c>();
        INV_DM_SqlQueryGenerator sqlQuery = new INV_DM_SqlQueryGenerator();         
        dmLoanScopeList = sqlQuery.getContractsForCurrentValidationScope(dmList);
        
        system.debug('scope list '+dmList.size()+ 'list '+dmLoanScopeList);                      
        INV_DM_Validation handler = new INV_DM_Validation();
        validationWrapperList = handler.validateDM(dmLoanScopeList);
        
        For(INV_DM_ValidationWrapper valWrapper : validationWrapperList){
            if(valWrapper.Success){          
                validationUpdate.add(new DM_Loan_Account__c(Id=valWrapper.Id, DM_Valid_Data__c=True, DM_Invalid_Data__c=False));      
                system.debug('validation Wrap Success');
            }else{
                //failed valWrapper send for updation
                system.debug('DM CL contract failed-->'+valWrapper.Id);
                validationUpdate.add(new DM_Loan_Account__c(Id=valWrapper.Id, DM_Error__c= valWrapper.errorMessage, DM_Invalid_Data__c=True, migration_status__c='Failed'));
            }
        }
        system.debug('update validated Record '+validationUpdate);
        //to remove duplicate id issue
        loanmap.putall(validationUpdate);
        if(loanmap.size()>0){
            update loanmap.values();
        }
        /*
        if(!validationUpdate.isEmpty()){
            update validationUpdate; 
        }*/
     
    }
    
    global void finish(Database.BatchableContext BC) {
         system.debug('Finish INV_DM_ValidationJob Batch Job');
    }
    
}//Class End