objects/DM_Loan_Account__c.object
<CustomObject>
    <fields>
        <fullName>DM_Is_Migrated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DM Is Migrated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DM_Valid_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DM Valid Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migration_Status__c</fullName>
        <label>Migration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DM CL Contract</label>
    <nameField>
        <label>DM Loan Con Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM CL Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Migration_Tool_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Execute_in_Start__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Execute in Start?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Child__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Child?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_Limit__c</fullName>
        <label>Query Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Query_String__c</fullName>
        <label>Query String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Migration Tool Configuration</label>
    <nameField>
        <displayFormat>CON# {00000000}</displayFormat>
        <label>Migration Tool Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Migration Tool Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/INV_DM_SqlQueryGenerator.cls
/******************************************************************************************************************
* Author: Samar Saha
* Date: Oct - 2019
* Update History - 
*****************************************************************************************************************/ 
public with sharing class INV_DM_SqlQueryGenerator 
{
    public String GetQueryStringForValidationStart(){
    
        List<Migration_Tool_Configuration__c> configList = [Select Id, 
                                                             Active__c, 
                                                             Is_Child__c, 
                                                             Object_API_Name__c, 
                                                             Object_Name__c,                                                              
                                                             Query_String__c 
                                                             from Migration_Tool_Configuration__c where Active__c = True and Execute_in_Start__c = True and Project_Name__c = 'Test'];
                                                             
        return configList[0].Query_String__c;
    }
    
    public List<DM_Loan_Account__c> GetContractsForCurrentScope(List<DM_Loan_Account__c> dmList)
    {
        List<DM_Loan_Account__c> dmLoanScopeList = new List<DM_Loan_Account__c>();
        string query ='';
        string parent='';
        string status='Pending';
        
        string parentField = '';
        string parentObjectAPIName = '';
        string finalQuery = '';
        
        List<Migration_Tool_Configuration__c> configList = [Select Id, 
                                                             Active__c, 
                                                             Is_Child__c, 
                                                             Object_API_Name__c, 
                                                             Object_Name__c, 
                                                             Query_Limit__c, 
                                                             Query_String__c 
                                                             from Migration_Tool_Configuration__c where Active__c = True and Execute_in_Start__c = False and Project_Name__c = 'Test'];
                                                             
        for(Migration_Tool_Configuration__c con : configList){
            if(con.Is_Child__c == True){
                query =  query + '(' + con.Query_String__c + '),';
            }
            else{
                parentField = con.Query_String__c;
                parentObjectAPIName = con.Object_API_Name__c;
                system.debug('*** Parent Object Name for Validation Job ***' + parentObjectAPIName);
            }        
        }
        
        query = query.removeEnd(',');                                       
        finalQuery = 'Select '+ parentField + ',' + query + ' from ' + parentObjectAPIName + 
                     ' where Migration_status__c = \'' +status+ '\' '+ 
                     ' and DM_Valid_Data__c = False';  
        system.debug('*** finalQuery --> ***' + finalQuery );
        
        //return finalQuery;
        dmLoanScopeList = Database.query(finalQuery);
        return dmLoanScopeList;           
    }
    
    public String GetQueryStringForMigration()
    {
        string query ='';
        string parent='';
        string status='pending';
        
        string parentField = '';
        string parentObjectAPIName = '';
        string finalQuery = '';
        
        List<Migration_Tool_Configuration__c> configList = [Select Id, 
                                                             Active__c, 
                                                             Is_Child__c, 
                                                             Object_API_Name__c, 
                                                             Object_Name__c, 
                                                             Query_Limit__c, 
                                                             Query_String__c 
                                                             from Migration_Tool_Configuration__c where Active__c = True and Execute_in_Start__c = False and Project_Name__c = 'Test'];
                                                             
        for(Migration_Tool_Configuration__c con : configList){
            if(con.Is_Child__c == True){
                query =  query + '(' + con.Query_String__c + '),';
            }
            else{
                parentField = con.Query_String__c;
                parentObjectAPIName = con.Object_API_Name__c;
                system.debug('*** Parent Object Name for migration Job ***' + parentObjectAPIName);
            }        
        }
        
        query = query.removeEnd(',');                                       
        finalQuery = 'Select '+ parentField + ',' + query + ' from ' + parentObjectAPIName + 
                     '  where Migration_Status__c = \'' + status + '\' ' + 
                     ' and DM_Is_Migrated__c = False and DM_Valid_Data__c = True';  
                     
        system.debug('*** finalQuery --> ***' + finalQuery );
        
        return finalQuery;                       
    }   
}